### ISSUE TITLE
リモート開催の方法を考える

### ISSUE THREAD

**Issue by mugi-uno** [toyamarb/meetup#5]
東京など、遠方からの参加者のためにリモート参加方法を考える。

ざっと思いつく考慮ポイントは以下かな？
- そもそも何を使うのか？(appear.in / skype / ustream / lync など)
- 安定したインターネット環境を確保できるか？（無線は辛い気がする）
- 会費はどう考えるか？（リモートはさすがに無料かなー？）

もくもく中はslackでニヤニヤしながらやりとり出来れば大丈夫っぽいので、
最初と最後だけうまくつながればなんとかなるような気はする。

**Comment by tkiha** [comment]
ネット回線が気になるけど、appear.inなどで繋ぎっぱで運用可能なのかやってみたいですね。
でも全員が繋ぐのは無理があるかなー。となるとリモート用のマシンが必要なのか。
うーむ。まぁ、まずはチャレンジですかねー

**Comment by kunitoo** [comment]
> - 会費はどう考えるか？（リモートはさすがに無料かなー？）

人数が多くなるなら、 doorkeeper のイベントを富山開催と東京サテライト開催の2つ立てる管理しやすかったりするかもと思いました。

**Comment by mugi-uno** [comment]
確かにリモート参加者と富山参加者は別管理としたほうが良さそうですね。

全員での接続は回線的に厳しくなる予感がします。
仮にappear.inと仮定したときに、
1. リモート側の会場をどうするか？
2. リモート接続専用のマシンを確保

は解決する必要があると思います。
1は伊藤さんにお願い可能だったりしますか？
仮に業務で利用されているオフィスとの接続となる場合、
一般募集をかけての参加は可能なのかも気になっています。

あとは、双方の会場が決まった時点で
可能であれば事前に接続の検証はしてみたいですね～

**Comment by kunitoo** [comment]
> 1は伊藤さんにお願い可能だったりしますか？

はい。私がやります。

永和が空いていれば、
https://www.doorkeeper.jp/%E4%BC%9A%E5%A0%B4/eiwa-systems-management
という感じなので、一般募集かけても問題ないです。
2. のマシンも確保できると思います。

**Comment by mugi-uno** [comment]
おー！なんて素敵な会場・・・
ありがとうございます。

それでは、Doorkeeperページの作成などは行いますので、
東京側の会場準備などはすいませんが伊藤さんにお願いします。
あとは早めに日付を決めたほうがいいですね。

kanazawa.rbが第三週なことなどを考えると、
第二週の 1/9 がいいのではないかと考えてますが、
永和さんは空いてそうな感じでしょうか？
（県民会館はまだ余裕がありそうです。）

年明け直後なので参加してくれるか少し心配ですが。。

あとはこちら側のリモート接続用のマシンの確保ですね。
確保できなければ、最初と最後だけ私のマシンを使って接続ですかね～

**Comment by kunitoo** [comment]
1/9 空いているので、場所おさえておきます。
13:00 - 18:00 でよいですか?

**Comment by mugi-uno** [comment]
okです。
今回はリモートでの開催がテーマになりそうなので、内容自体は前回と同じもくもく会にしましょう。

Doorkeeperも作りますね。
とりあえず、双方10人ずつの定員にしておきますね。

**Comment by kunitoo** [comment]
はい！Doorkeeperよろしくお願いします！

**Comment by mugi-uno** [comment]
to 木原さん
私の方で富山/東京双方のDoorkeeperは作りますので、
すいませんが、県民会館の予約をお願いしても良いでしょうか？
http://www.bunka-toyama.jp/kenminkaikan/use-reservation/index.html
から申し込む感じです。
狙い目は 306 / 505 / 602〜607 / 703 あたりの部屋です。
（私に隕石が落ちてきて参加できなくなったとしても、
　イベント自体は継続して開催できるよう、準備で必要な作業は共有しておきましょうー！）

to 伊藤さん
東京側会場の参加費はどうしましょうか。
雰囲気的に無料ですか？（そうだとしたらうらやましい。。）

さて、あとはToyamaFreeWiFiでのビデオ通話が非常に心配ですね〜

回線
a. ToyamaFreeWifi
b. 麦島のiPhoneでテザリング
 （テザリングしたmacと別のiphoneをappear.inで繋いだ感じは意外といけそうでした）

方法
1. appear.in
2. hangout
3. skype

と考えて、基本は a + 1 を想定しておいて、
ダメなら他の組み合わせも試してみましょう。

**Comment by tkiha** [comment]
はーい。やっておきますー!

**Comment by mugi-uno** [comment]
イベントページを作成しました。

富山　https://toyamarb.doorkeeper.jp/events/36034
東京　https://toyamarb.doorkeeper.jp/events/36039

ちなみに、お二人にDoorkeeperの主催者権限も付与しておきました。
特別何かしてほしい！ということではありませんが、
何か特記事項や訂正などがある場合は、自由に修正して頂いてokです。

**Comment by mugi-uno** [comment]
富山会場側のライブ中継方法について、少し検証してみました。
iphone6s + 4G + appear.in で、遠隔端末と接続してみましたが、
それだけでも遠隔端末側でそれなりに綺麗に見えたそうで、
会場のwifiが死んでてもぎりぎりそれで接続はできそうな感じです。

理想は高解像度のwebカメラを用意できることですが、
現状だと用意できる見込みがございません。。

ビデオカメラを接続するともう少し綺麗に中継できるという話も聞いたので、
それもちょっと試してみます。

**Comment by mugi-uno** [comment]
同日の同時刻に、西脇.rb & 神戸.rb の方でも 勉強会を開催するらしく、
そちらも東京とのリモート接続を行うとのことで、
西脇.rb 主催の伊藤さんより、せっかくなので少しの時間だけ繋いで何かやってみませんかー？
というご提案を受けております。

面白そうですし、せっかくの機会なのでやってみてはどうかな～と思っています。
15時ぐらいから短い時間(30分ほど)の間、
富山, 神戸, 東京(toyama.rb), 東京(西脇&神戸.rb) の4地点で接続します。
具体的にその時間で何をするかは現在ちょっと相談中でございます。

15時頃になったタイミングでappear.inの接続を行う必要があるので、
その際にはすいませんがご協力をお願いします～！

**Comment by kunitoo** [comment]
準備しておきます
