### ISSUE TITLE
#02 詳細を決める

### ISSUE THREAD

**Issue by mugi-uno** [toyamarb/meetup#6]
- 日程
- 内容
- 会場
- 懇親会

**Comment by tkiha** [comment]
#### 県民会館を予約済み
- 2016/1/9 12:00-18:00 で予約
- 小会議室603号室（最大12名定員）

マイク・スクリーン等の付属設備が必要な場合は別途料金とのことです。（要らないかな

**Comment by mugi-uno** [comment]
おお、早い！ありがとうございます。

> マイク・スクリーン等の付属設備が必要な場合は別途料金とのことです。

前回のように壁に投影すればいいと思いますので、無くても大丈夫かと～
人数がもっともっと増えるようであれば借りる必要があるかもしれませんが、
到底は大丈夫だと思います。

（プロジェクタは再度うちの社内から拝借予定

**Comment by mugi-uno** [comment]
（本日中にはdoorkeeper公開予定）

**Comment by mugi-uno** [comment]
doorkeeper作成完了

富山　https://toyamarb.doorkeeper.jp/events/36034
東京　https://toyamarb.doorkeeper.jp/events/36039

**Comment by mugi-uno** [comment]
無事終了ー！
